### ISSUE TITLE
Extra level of abstraction increases code complexity

### ISSUE THREAD

**Issue by vitalk** [ilyaborodin/LeverX_task_4#10]
https://github.com/ilyaborodin/LeverX_task_4/blob/3c513bcee0d021943f3e68e083eac627008aa5ee/main.py#L20

Overengineering with converter. Any reason to use converter at all? It's loosely-coupled with all your classes and main entry point. You can just use simple data structures in your interfaces and this reduces the complexity of your code. Internally you can change repr of data your operate, but for end-users of your class the interface should be simple, e.g. instead of

```
rooms = converter.convert_to_rooms(whatever)
db_manager.load_in_db(rooms)
top_5_students = db_manager.get_top_5_students()
ohnn: list = converter.convert_to_list_of_whatever(top_5_students)
```

you can do this

```
db_manager.load_in_db(list_of_rooms)
top_5_students = db_manager.get_top_5_students()

class DbManager:
    def load_in_db(self, rooms: List[Dict]):
        internal_rooms_repr = self._convert_to_internal_repr(rooms)

    def get_top_5_students(self) -> List[Dict]:
        internal_repr_of_result = ...
        return self._convert_to_external_repr(internal_repr_of_result)
```

**Comment by ilyaborodin** [comment]
I left only 2 methods in converter that are responsible for converting output from database to format [{}, {}]. I decided to leave the converter, because data from database comes with a different number of fields and several variations with the conversion are needed.
