### ISSUE TITLE
Create abstract class to access db and reuse it

### ISSUE THREAD

**Issue by vitalk** [ilyaborodin/LeverX_task_4#11]
https://github.com/ilyaborodin/LeverX_task_4/blob/3c513bcee0d021943f3e68e083eac627008aa5ee/rooms.py#L25

room_db and students_db have some duplicated logic and can be inherited from base class to reuse some common parts and reduce code duplication.

```
class DbManager:
    def execute_query(self, sql_query: str):
        with self.mysql_connector(self.data_mysql) as db:
            return db.query(sql_query)
```

**Comment by ilyaborodin** [comment]
Done
