### ISSUE TITLE
Use Union[list, dict] instead

### ISSUE THREAD

**Issue by vitalk** [ilyaborodin/LeverX_task_4#9]
https://github.com/ilyaborodin/LeverX_task_4/blob/3c513bcee0d021943f3e68e083eac627008aa5ee/data_exporter.py#L8

This construction is wrong, e.g. 

```
list or dict -> bool 
def whatever(a: bool):  # <! - I suppose this is not expected result here
    pass
```

**Comment by ilyaborodin** [comment]
Done
